### ISSUE TITLE
ast2 TODO list

### ISSUE THREAD

**Issue by genotrance** [nimterop/nimterop#195]
Support for additional C constructs:
- [ ] Variables - regular and arrays (proc vars are already supported)
- [ ] static const
- [ ] `{.size.}` pragma where appropriate
- [ ] `cstringArray` in place of `char **`
- [ ] Default values for params (cute_math.h)

Other functionality:
- [ ] `cOverride()` support for vars and consts
- [ ] Use `-d:checkAbi` to verify size of type wrappers is correct
